### ISSUE TITLE
Story Plugin

### ISSUE THREAD

**Issue by ryanelian** [Arks-Layer/PSO2Tweaker#33]
Now, with the patching issues (hopefully) behind us, I would like to take a hard, closer look into the matter of Story Translation in-game.

I'll start with the cold hard truth. Story Patch is wasted effort and shouldn't exist in current form, because AIDA said this in the forum:

> Once I come up with a method to avoid taking a ridiculous amount of time to correct all the issues, only to have it break again 3 days later, I'll have news. Also keep in mind that everyone who works on this stuff has lives and (usually) full time jobs.
> 
> The story patch doesn't "break" anything - Parts of it are untranslated because SEGA seemed to decide halfway through EPISODE 3 that they wanted branching timelines and stories, so they split up a LOT of story stuff from (random example) 1001 to 1001a/1001b/1002, which broke every single scene that they did that to. Then, they didn't use a consistent system to name the new scenes, and even put the split pieces into new ice files (stupid stuff like this is why you have 48,000 files in your data folder) so I'd have to find them all over again, find each piece, and retranslate the scene, which was incredibly time-consuming. Then, to rub salt in the wound, then went back and changed a LOT more (sometimes the SAME THINGS they just changed) of the story each maint, so I would have to do it again each maintenance.
> 
> So to reiterate - once I have a more concrete method that doesn't make me want to punch baby rappies, there will be news. 

It is a gargantuan effort to find needles in a haystack when the haystack randomly changes itself every once in a while like a living maze. Not cool.

Also, unlike the English Large Files, Story Patch takes awhile to patch due to the sheer number of files it need to modify.

Instead we should do this the JIT way, which I've written in the forum too:

> Solution 2: Plugin-Based
> 
> We can tackle the situation using other approach that will never break ever, unless the story text gets changed.
> 
> Supposedly there's a way to detect and intercept the routine whenever an NPC is talking or whenever a player choice comes out, you can create a translation dictionary indexed by NPC name / ID.
> 
> りさ : "こんにちは!"
> Translated would be --> Lisa: "hello!"
> 
> Create a dictionary using this format:
> NPC[ID / Name][Sentence Hash] = String
> NPC[りさ][MD5 or SHA1 or SHA256 of "こんにちは!"] = "hello!"
> 
> If the spoken text translation is found, display instead. Otherwise display the original text.
> 
> You guys could intercept item translation, damage and title list using plugins. And even the block names / announcements when using PSO2Proxy. So theoretically it's possible with game story script too! 

---
## Task:
- [ ] Evaluate the capabilities of PSO2 Tweaker plugin system.
- [ ] Evaluate whether that plugin system can capture an NPC conversation by name or ID and speech content.
- [ ] Evaluate whether the plugin system can replace texts before or after it's displayed.
- [ ] If all possible, develop a working story plugin!
- [ ] Then port the actual story translation to this plugin.
- [ ] After that, create a website that can accept untranslated story lines (using web service from and to Tweaker) and can accept community translation.

**Comment by acffordyce973** [comment]
@VariantXYZ should be able to shed some light on this.

**Comment by VariantXYZ** [comment]
Mm... I was working on a plugin a while back to load files from a directory whenever the game looked for them (that is, check a main folder first, then fallback into the default game folder if it doesn't exist). Unfortunately, right now it just does that for ICE files, which I guess would work for mods as they are now.

That being said, in theory what's being proposed is possible, it's just R&D and I don't know who (with the necessary skillset) has the time right now to look into it.

I imagine you could do one of the following:
1. Hook the NIFL/Text loading procedure
2. Hook the ICE file class method to get specific files
3. Modify the lua itself for dialogue to load different files (this would be a lot of work I bet)

I'm sure there might be some others that I can't think off the top of my head right now, but that's the current situation...

**Comment by ryanelian** [comment]
How do you create a plugin anyway? Is it not .NET?

**Comment by VariantXYZ** [comment]
The libraries are C++ based off a core library (pso2h), which I was planning on releasing (that is, closed source core library, and open source plugins), but I never got around to it :|

Maybe you can convince Alam to take over and make it release-worthy :D

**Comment by ryanelian** [comment]
> The libraries are C++ based off a core library (pso2h),

Fucking hell. That's hardcore.

> Maybe you can convince Alam to take over and make it release-worthy :D

I'm interested in taking a look first but honestly a take over is a bit too much for me. :skull:

**Comment by alama** [comment]
You want me to be a Release Manager for pso2h? hahahahahah.....

**Comment by TheCrimsonDevil** [comment]
Oh God if Alam takes over... DOOM.

**Comment by alama** [comment]
oh, I could do it, just, do I keep pso2h core private and move the other plugins into submodules and make a new submodule name "SDK" so people outside of Arks-Layer can make their own plugins?

Or do we can still keep it all private?

**Comment by ryanelian** [comment]
> oh, I could do it, just, do I keep pso2h core private and move the other plugins into submodules and make a new submodule name "SDK" so people outside of Arks-Layer can make their own plugins?

> Or do we can still keep it all private?

Since the damage parsers are banned by SEGA due to its widespread use by our Japanese friends, I am actually quite interested in what happens if you decided to release the source in the wild.

We might be able to see weird shenanigans from forked from that.

**Comment by TheCrimsonDevil** [comment]
That "SDK but keep pso2h private" sounds great! We already have a report
for pso2h, did you want me to throw a SDK repo up and make you admin of a
SDK team? (Or just use the existing plugin team).

I can do that at work if so, just let me know ^^

**Comment by alama** [comment]
me and my big mouth:
*pick up huge git handbook*

Ok, how do I use git-submodule and git-filterbranch

I want to keep the git history intact for the most part

**Comment by VariantXYZ** [comment]
Yeah, pso2h would just provide binaries (DLL/Lib/.h for exports), and then just have the plugins as their own repos. You shouldn't need to submodule in this case, the dependency is pso2h, but it's a binary dependency not a source dependency in this case...

@alama if you convert pso2h from C++ to C, people could more easily make plugins in C# ;)

**Comment by TheCrimsonDevil** [comment]
https://github.com/Arks-Layer/TweakerPluginSDK

Alam is the Team Maintainer. Feel free to change the name if you wish (and
add whoever you want to the Plugin Team).

**Comment by TheCrimsonDevil** [comment]
Also keep in mind this repo is public :3

**Comment by VariantXYZ** [comment]
@ryanelian 

> What if you don't deal with routing other files but instead just deal with the text that is loaded from the files? I mean, just store all the translation in-memory instead of in a separate file.

The core issue is that the ICE files themselves have story text swapped sometimes between patches IIRC, so if we can simply make it so that whatever SEGA does to the ICE filenames has minimal impact on us, then that's perfect. 

That is to say, today we might see 1001 in ICE archive A, but tomorrow it might be in ICE archive B due to an update. Correct me if I'm misunderstanding the issue with the story patch @TheCrimsonDevil.

If we do it by updating the lua itself for events, it might be fine... but we'd need to find all of those (which we can't do just by scanning for text).

If it's just a matter of text stuff, I honestly think the best course of action is just to hook how the game reads NIFL/Text, which should be static (that is, the lua refers to the NIFL files). We definitely know these file names (we replace them).

**Comment by belldandu** [comment]
I might want to get in on this but depends on how others feel about that.

**Comment by VariantXYZ** [comment]
Oh right, it's worth noting that people probably already think the plugins stuff is way too shady, so I'd like to avoid porting things to it anyway if we can avoid it. The assumptions it works on are more fragile than the story/english/large files patch assumptions, and SEGA/GG definitely have some issue with the plugins as-is.

I'm sure if we wanted to we could automate the way the story patch is built now anyway, or make a user/client-side executable that would automate the file naming and repacking. It's not like all the ICE stuff isn't already public anyway.

**Comment by belldandu** [comment]
Ignored *feelsbadman*

**Comment by DeleteIT** [comment]
So, is it safe to assume this never got resolved?

**Comment by Kyle873** [comment]
Maybe someday, but right now everyone who has the skills to really pick up and do this is already stretched thin as it is.

**Comment by DeleteIT** [comment]
Is there an example of the method currently used to translate, or at least parse the information from the files?

Since there's already CSV files for other languages hosted on GitHub, I feel it would make the most sense to just have a client sided tool that does the patching, from the appropriate language repo.

**Comment by TheCrimsonDevil** [comment]
Not at the moment - However, this problem is being resolved internally and will be fixed "shortly".
